### ISSUE TITLE
Crash in truncate_date():lib/nom.rb during initial run

### ISSUE THREAD

**Issue by spekode** [blinry/nom#2]
When running nom for the first time you get an error.

Error:
nom/nom.rb:286:in `-': expected numeric (TypeError)

truncate_date tries to subtract @weights.last_real before there are any weights recorded, so @weights.last_real is nil.

**Comment by blinry** [comment]
Oh my, kind of a worst-case bug that was introduced after reordering some code. Thanks for reporting!
